//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: mahjon.proto
namespace pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LackCard")]
  public partial class LackCard : global::ProtoBuf.IExtensible
  {
    public LackCard() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private pb.CardType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.CardType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardInfo")]
  public partial class CardInfo : global::ProtoBuf.IExtensible
  {
    public CardInfo() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _CardOid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"CardOid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int CardOid
    {
      get { return _CardOid; }
      set { _CardOid = value; }
    }
    private int _CardId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"CardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int CardId
    {
      get { return _CardId; }
      set { _CardId = value; }
    }
    private pb.CardStatus _Status;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.CardStatus Status
    {
      get { return _Status; }
      set { _Status = value; }
    }
    private bool _fromOther = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fromOther", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool fromOther
    {
      get { return _fromOther; }
      set { _fromOther = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattlePlayerInfo")]
  public partial class BattlePlayerInfo : global::ProtoBuf.IExtensible
  {
    public BattlePlayerInfo() {}
    
    private pb.BattleSide _side;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"side", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.BattleSide side
    {
      get { return _side; }
      set { _side = value; }
    }
    private bool _isOwner;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isOwner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isOwner
    {
      get { return _isOwner; }
      set { _isOwner = value; }
    }
    private pb.PlayerInfo _player;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public pb.PlayerInfo player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private int _oid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"oid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int oid
    {
      get { return _oid; }
      set { _oid = value; }
    }
    private string _nickName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private string _headIcon;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"headIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string headIcon
    {
      get { return _headIcon; }
      set { _headIcon = value; }
    }
    private int _gold;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _diamond;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSLogin")]
  public partial class C2GSLogin : global::ProtoBuf.IExtensible
  {
    public C2GSLogin() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CLoginRet")]
  public partial class GS2CLoginRet : global::ProtoBuf.IExtensible
  {
    public GS2CLoginRet() {}
    
    private pb.GS2CLoginRet.ErrorCode _errorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.GS2CLoginRet.ErrorCode errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private pb.PlayerInfo _playerInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb.PlayerInfo playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACCOUNT_ERROR", Value=2)]
      ACCOUNT_ERROR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PASSWORD_ERROR", Value=3)]
      PASSWORD_ERROR = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=4)]
      FAIL = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSEnterGame")]
  public partial class C2GSEnterGame : global::ProtoBuf.IExtensible
  {
    public C2GSEnterGame() {}
    
    private pb.GameMode _mode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.GameMode mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private string _roomId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CEnterGameRet")]
  public partial class GS2CEnterGameRet : global::ProtoBuf.IExtensible
  {
    public GS2CEnterGameRet() {}
    
    private pb.GS2CEnterGameRet.ErrorCode _errorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.GS2CEnterGameRet.ErrorCode errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private pb.GameMode _mode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.GameMode mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private string _roomId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=2)]
      FAIL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_COUNT_LIMITE", Value=3)]
      PLAYER_COUNT_LIMITE = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CUpdateRoomInfo")]
  public partial class GS2CUpdateRoomInfo : global::ProtoBuf.IExtensible
  {
    public GS2CUpdateRoomInfo() {}
    
    private readonly global::System.Collections.Generic.List<pb.BattlePlayerInfo> _player = new global::System.Collections.Generic.List<pb.BattlePlayerInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.BattlePlayerInfo> player
    {
      get { return _player; }
    }
  
    private pb.GS2CUpdateRoomInfo.Status _status;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.GS2CUpdateRoomInfo.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Status")]
    public enum Status
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADD", Value=1)]
      ADD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REMOVE", Value=2)]
      REMOVE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE", Value=3)]
      UPDATE = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CBattleStart")]
  public partial class GS2CBattleStart : global::ProtoBuf.IExtensible
  {
    public GS2CBattleStart() {}
    
    private int _dealerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dealerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dealerId
    {
      get { return _dealerId; }
      set { _dealerId = value; }
    }
    private readonly global::System.Collections.Generic.List<pb.CardInfo> _cardList = new global::System.Collections.Generic.List<pb.CardInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.CardInfo> cardList
    {
      get { return _cardList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSExchangeCard")]
  public partial class C2GSExchangeCard : global::ProtoBuf.IExtensible
  {
    public C2GSExchangeCard() {}
    
    private readonly global::System.Collections.Generic.List<pb.CardInfo> _cardList = new global::System.Collections.Generic.List<pb.CardInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.CardInfo> cardList
    {
      get { return _cardList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CExchangeCardRet")]
  public partial class GS2CExchangeCardRet : global::ProtoBuf.IExtensible
  {
    public GS2CExchangeCardRet() {}
    
    private pb.GS2CExchangeCardRet.ErrorCode _errorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.GS2CExchangeCardRet.ErrorCode errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=2)]
      FAIL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_CARD_COUNT_ERROR", Value=3)]
      FAIL_CARD_COUNT_ERROR = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CUpdateCardInfoAfterExchange")]
  public partial class GS2CUpdateCardInfoAfterExchange : global::ProtoBuf.IExtensible
  {
    public GS2CUpdateCardInfoAfterExchange() {}
    
    private pb.ExchangeType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.ExchangeType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<pb.CardInfo> _cardList = new global::System.Collections.Generic.List<pb.CardInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.CardInfo> cardList
    {
      get { return _cardList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSSelectLack")]
  public partial class C2GSSelectLack : global::ProtoBuf.IExtensible
  {
    public C2GSSelectLack() {}
    
    private pb.CardType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.CardType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CSelectLackRet")]
  public partial class GS2CSelectLackRet : global::ProtoBuf.IExtensible
  {
    public GS2CSelectLackRet() {}
    
    private readonly global::System.Collections.Generic.List<pb.LackCard> _lackCard = new global::System.Collections.Generic.List<pb.LackCard>();
    [global::ProtoBuf.ProtoMember(1, Name=@"lackCard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.LackCard> lackCard
    {
      get { return _lackCard; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSDiscard")]
  public partial class C2GSDiscard : global::ProtoBuf.IExtensible
  {
    public C2GSDiscard() {}
    
    private int _cardOid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cardOid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cardOid
    {
      get { return _cardOid; }
      set { _cardOid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CDiscardRet")]
  public partial class GS2CDiscardRet : global::ProtoBuf.IExtensible
  {
    public GS2CDiscardRet() {}
    
    private int _cardOid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cardOid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cardOid
    {
      get { return _cardOid; }
      set { _cardOid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSCurTurnOver")]
  public partial class C2GSCurTurnOver : global::ProtoBuf.IExtensible
  {
    public C2GSCurTurnOver() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CTurnToNext")]
  public partial class GS2CTurnToNext : global::ProtoBuf.IExtensible
  {
    public GS2CTurnToNext() {}
    
    private int _playerOid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerOid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerOid
    {
      get { return _playerOid; }
      set { _playerOid = value; }
    }
    private pb.CardInfo _card = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb.CardInfo card
    {
      get { return _card; }
      set { _card = value; }
    }
    private pb.TurnSwitchType _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.TurnSwitchType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CRobotProc")]
  public partial class GS2CRobotProc : global::ProtoBuf.IExtensible
  {
    public GS2CRobotProc() {}
    
    private int _procPlayer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"procPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int procPlayer
    {
      get { return _procPlayer; }
      set { _procPlayer = value; }
    }
    private pb.ProcType _procType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"procType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.ProcType procType
    {
      get { return _procType; }
      set { _procType = value; }
    }
    private int _beProcPlayer = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"beProcPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int beProcPlayer
    {
      get { return _beProcPlayer; }
      set { _beProcPlayer = value; }
    }
    private readonly global::System.Collections.Generic.List<pb.CardInfo> _cardList = new global::System.Collections.Generic.List<pb.CardInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"cardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.CardInfo> cardList
    {
      get { return _cardList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSRobotProcOver")]
  public partial class C2GSRobotProcOver : global::ProtoBuf.IExtensible
  {
    public C2GSRobotProcOver() {}
    
    private int _robotOid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"robotOid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int robotOid
    {
      get { return _robotOid; }
      set { _robotOid = value; }
    }
    private pb.ProcType _procType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"procType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.ProcType procType
    {
      get { return _procType; }
      set { _procType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CPlayerEnsureProc")]
  public partial class GS2CPlayerEnsureProc : global::ProtoBuf.IExtensible
  {
    public GS2CPlayerEnsureProc() {}
    
    private int _procPlayer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"procPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int procPlayer
    {
      get { return _procPlayer; }
      set { _procPlayer = value; }
    }
    private pb.ProcType _procType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"procType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.ProcType procType
    {
      get { return _procType; }
      set { _procType = value; }
    }
    private int _beProcPlayer = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"beProcPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int beProcPlayer
    {
      get { return _beProcPlayer; }
      set { _beProcPlayer = value; }
    }
    private int _procCardId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"procCardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int procCardId
    {
      get { return _procCardId; }
      set { _procCardId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSPlayerEnsureProcRet")]
  public partial class C2GSPlayerEnsureProcRet : global::ProtoBuf.IExtensible
  {
    public C2GSPlayerEnsureProcRet() {}
    
    private pb.ProcType _procType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"procType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.ProcType procType
    {
      get { return _procType; }
      set { _procType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CUpdateCardAfterPlayerProc")]
  public partial class GS2CUpdateCardAfterPlayerProc : global::ProtoBuf.IExtensible
  {
    public GS2CUpdateCardAfterPlayerProc() {}
    
    private readonly global::System.Collections.Generic.List<pb.CardInfo> _cardList = new global::System.Collections.Generic.List<pb.CardInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.CardInfo> cardList
    {
      get { return _cardList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameMode")]
    public enum GameMode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"JoinRoom", Value=1)]
      JoinRoom = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateRoom", Value=2)]
      CreateRoom = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QuickEnter", Value=3)]
      QuickEnter = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BattleSide")]
    public enum BattleSide
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"east", Value=1)]
      east = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"south", Value=2)]
      south = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"west", Value=3)]
      west = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"north", Value=4)]
      north = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"none", Value=5)]
      none = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CardStatus")]
    public enum CardStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"noDeal", Value=1)]
      noDeal = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"inHand", Value=2)]
      inHand = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"bePeng", Value=3)]
      bePeng = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"beGang", Value=4)]
      beGang = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"discard", Value=5)]
      discard = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"hu", Value=6)]
      hu = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CardType")]
    public enum CardType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Wan", Value=1)]
      Wan = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Tiao", Value=2)]
      Tiao = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Tong", Value=3)]
      Tong = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"None", Value=4)]
      None = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ExchangeType")]
    public enum ExchangeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClockWise", Value=1)]
      ClockWise = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AntiClock", Value=2)]
      AntiClock = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Opposite", Value=3)]
      Opposite = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProcType")]
    public enum ProcType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SelfGang", Value=1)]
      SelfGang = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GangOther", Value=2)]
      GangOther = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Peng", Value=3)]
      Peng = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SelfHu", Value=4)]
      SelfHu = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HuOther", Value=5)]
      HuOther = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TurnSwitchType")]
    public enum TurnSwitchType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Normal", Value=1)]
      Normal = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JustCanDiscard", Value=2)]
      JustCanDiscard = 2
    }
  
}