// Code generated by protoc-gen-go.
// source: mahjon.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	mahjon.proto

It has these top-level messages:
	LackCard
	CardInfo
	BattlePlayerInfo
	PlayerInfo
	C2GSLogin
	GS2CLoginRet
	C2GSEnterGame
	GS2CEnterGameRet
	GS2CUpdateRoomInfo
	GS2CBattleStart
	C2GSExchangeCard
	GS2CExchangeCardRet
	GS2CUpdateExchangeOverPlayer
	GS2CUpdateCardInfoAfterExchange
	C2GSSelectLack
	GS2CSelectLackRet
	GS2CDiscardTimeOut
	C2GSDiscard
	GS2CDiscardRet
	GS2CDealCard
	C2GSWin
	GS2CWinRet
*/
package pb

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type GameMode int32

const (
	GameMode_JoinRoom   GameMode = 1
	GameMode_CreateRoom GameMode = 2
	GameMode_QuickEnter GameMode = 3
)

var GameMode_name = map[int32]string{
	1: "JoinRoom",
	2: "CreateRoom",
	3: "QuickEnter",
}
var GameMode_value = map[string]int32{
	"JoinRoom":   1,
	"CreateRoom": 2,
	"QuickEnter": 3,
}

func (x GameMode) Enum() *GameMode {
	p := new(GameMode)
	*p = x
	return p
}
func (x GameMode) String() string {
	return proto.EnumName(GameMode_name, int32(x))
}
func (x *GameMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GameMode_value, data, "GameMode")
	if err != nil {
		return err
	}
	*x = GameMode(value)
	return nil
}

type BattleSide int32

const (
	BattleSide_east  BattleSide = 1
	BattleSide_south BattleSide = 2
	BattleSide_west  BattleSide = 3
	BattleSide_north BattleSide = 4
	BattleSide_none  BattleSide = 5
)

var BattleSide_name = map[int32]string{
	1: "east",
	2: "south",
	3: "west",
	4: "north",
	5: "none",
}
var BattleSide_value = map[string]int32{
	"east":  1,
	"south": 2,
	"west":  3,
	"north": 4,
	"none":  5,
}

func (x BattleSide) Enum() *BattleSide {
	p := new(BattleSide)
	*p = x
	return p
}
func (x BattleSide) String() string {
	return proto.EnumName(BattleSide_name, int32(x))
}
func (x *BattleSide) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BattleSide_value, data, "BattleSide")
	if err != nil {
		return err
	}
	*x = BattleSide(value)
	return nil
}

type CardStatus int32

const (
	CardStatus_noDeal CardStatus = 1
	CardStatus_inHand CardStatus = 2
	CardStatus_bePeng CardStatus = 3
	CardStatus_beGang CardStatus = 4
	CardStatus_dicard CardStatus = 5
)

var CardStatus_name = map[int32]string{
	1: "noDeal",
	2: "inHand",
	3: "bePeng",
	4: "beGang",
	5: "dicard",
}
var CardStatus_value = map[string]int32{
	"noDeal": 1,
	"inHand": 2,
	"bePeng": 3,
	"beGang": 4,
	"dicard": 5,
}

func (x CardStatus) Enum() *CardStatus {
	p := new(CardStatus)
	*p = x
	return p
}
func (x CardStatus) String() string {
	return proto.EnumName(CardStatus_name, int32(x))
}
func (x *CardStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CardStatus_value, data, "CardStatus")
	if err != nil {
		return err
	}
	*x = CardStatus(value)
	return nil
}

type CardType int32

const (
	CardType_Wan  CardType = 1
	CardType_Tiao CardType = 2
	CardType_Tong CardType = 3
	CardType_None CardType = 4
)

var CardType_name = map[int32]string{
	1: "Wan",
	2: "Tiao",
	3: "Tong",
	4: "None",
}
var CardType_value = map[string]int32{
	"Wan":  1,
	"Tiao": 2,
	"Tong": 3,
	"None": 4,
}

func (x CardType) Enum() *CardType {
	p := new(CardType)
	*p = x
	return p
}
func (x CardType) String() string {
	return proto.EnumName(CardType_name, int32(x))
}
func (x *CardType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CardType_value, data, "CardType")
	if err != nil {
		return err
	}
	*x = CardType(value)
	return nil
}

type DisacardStatus int32

const (
	DisacardStatus_default DisacardStatus = 1
	DisacardStatus_peng    DisacardStatus = 2
	DisacardStatus_gang    DisacardStatus = 3
	DisacardStatus_ting    DisacardStatus = 4
)

var DisacardStatus_name = map[int32]string{
	1: "default",
	2: "peng",
	3: "gang",
	4: "ting",
}
var DisacardStatus_value = map[string]int32{
	"default": 1,
	"peng":    2,
	"gang":    3,
	"ting":    4,
}

func (x DisacardStatus) Enum() *DisacardStatus {
	p := new(DisacardStatus)
	*p = x
	return p
}
func (x DisacardStatus) String() string {
	return proto.EnumName(DisacardStatus_name, int32(x))
}
func (x *DisacardStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DisacardStatus_value, data, "DisacardStatus")
	if err != nil {
		return err
	}
	*x = DisacardStatus(value)
	return nil
}

type GS2CLoginRet_ErrorCode int32

const (
	GS2CLoginRet_SUCCESS        GS2CLoginRet_ErrorCode = 1
	GS2CLoginRet_ACCOUNT_ERROR  GS2CLoginRet_ErrorCode = 2
	GS2CLoginRet_PASSWORD_ERROR GS2CLoginRet_ErrorCode = 3
	GS2CLoginRet_FAIL           GS2CLoginRet_ErrorCode = 4
)

var GS2CLoginRet_ErrorCode_name = map[int32]string{
	1: "SUCCESS",
	2: "ACCOUNT_ERROR",
	3: "PASSWORD_ERROR",
	4: "FAIL",
}
var GS2CLoginRet_ErrorCode_value = map[string]int32{
	"SUCCESS":        1,
	"ACCOUNT_ERROR":  2,
	"PASSWORD_ERROR": 3,
	"FAIL":           4,
}

func (x GS2CLoginRet_ErrorCode) Enum() *GS2CLoginRet_ErrorCode {
	p := new(GS2CLoginRet_ErrorCode)
	*p = x
	return p
}
func (x GS2CLoginRet_ErrorCode) String() string {
	return proto.EnumName(GS2CLoginRet_ErrorCode_name, int32(x))
}
func (x *GS2CLoginRet_ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GS2CLoginRet_ErrorCode_value, data, "GS2CLoginRet_ErrorCode")
	if err != nil {
		return err
	}
	*x = GS2CLoginRet_ErrorCode(value)
	return nil
}

type GS2CEnterGameRet_ErrorCode int32

const (
	GS2CEnterGameRet_SUCCESS             GS2CEnterGameRet_ErrorCode = 1
	GS2CEnterGameRet_FAIL                GS2CEnterGameRet_ErrorCode = 2
	GS2CEnterGameRet_PLAYER_COUNT_LIMITE GS2CEnterGameRet_ErrorCode = 3
)

var GS2CEnterGameRet_ErrorCode_name = map[int32]string{
	1: "SUCCESS",
	2: "FAIL",
	3: "PLAYER_COUNT_LIMITE",
}
var GS2CEnterGameRet_ErrorCode_value = map[string]int32{
	"SUCCESS":             1,
	"FAIL":                2,
	"PLAYER_COUNT_LIMITE": 3,
}

func (x GS2CEnterGameRet_ErrorCode) Enum() *GS2CEnterGameRet_ErrorCode {
	p := new(GS2CEnterGameRet_ErrorCode)
	*p = x
	return p
}
func (x GS2CEnterGameRet_ErrorCode) String() string {
	return proto.EnumName(GS2CEnterGameRet_ErrorCode_name, int32(x))
}
func (x *GS2CEnterGameRet_ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GS2CEnterGameRet_ErrorCode_value, data, "GS2CEnterGameRet_ErrorCode")
	if err != nil {
		return err
	}
	*x = GS2CEnterGameRet_ErrorCode(value)
	return nil
}

type GS2CUpdateRoomInfo_Status int32

const (
	GS2CUpdateRoomInfo_ADD    GS2CUpdateRoomInfo_Status = 1
	GS2CUpdateRoomInfo_REMOVE GS2CUpdateRoomInfo_Status = 2
	GS2CUpdateRoomInfo_UPDATE GS2CUpdateRoomInfo_Status = 3
)

var GS2CUpdateRoomInfo_Status_name = map[int32]string{
	1: "ADD",
	2: "REMOVE",
	3: "UPDATE",
}
var GS2CUpdateRoomInfo_Status_value = map[string]int32{
	"ADD":    1,
	"REMOVE": 2,
	"UPDATE": 3,
}

func (x GS2CUpdateRoomInfo_Status) Enum() *GS2CUpdateRoomInfo_Status {
	p := new(GS2CUpdateRoomInfo_Status)
	*p = x
	return p
}
func (x GS2CUpdateRoomInfo_Status) String() string {
	return proto.EnumName(GS2CUpdateRoomInfo_Status_name, int32(x))
}
func (x *GS2CUpdateRoomInfo_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GS2CUpdateRoomInfo_Status_value, data, "GS2CUpdateRoomInfo_Status")
	if err != nil {
		return err
	}
	*x = GS2CUpdateRoomInfo_Status(value)
	return nil
}

type GS2CExchangeCardRet_ErrorCode int32

const (
	GS2CExchangeCardRet_SUCCESS               GS2CExchangeCardRet_ErrorCode = 1
	GS2CExchangeCardRet_FAIL                  GS2CExchangeCardRet_ErrorCode = 2
	GS2CExchangeCardRet_FAIL_CARD_COUNT_ERROR GS2CExchangeCardRet_ErrorCode = 3
)

var GS2CExchangeCardRet_ErrorCode_name = map[int32]string{
	1: "SUCCESS",
	2: "FAIL",
	3: "FAIL_CARD_COUNT_ERROR",
}
var GS2CExchangeCardRet_ErrorCode_value = map[string]int32{
	"SUCCESS":               1,
	"FAIL":                  2,
	"FAIL_CARD_COUNT_ERROR": 3,
}

func (x GS2CExchangeCardRet_ErrorCode) Enum() *GS2CExchangeCardRet_ErrorCode {
	p := new(GS2CExchangeCardRet_ErrorCode)
	*p = x
	return p
}
func (x GS2CExchangeCardRet_ErrorCode) String() string {
	return proto.EnumName(GS2CExchangeCardRet_ErrorCode_name, int32(x))
}
func (x *GS2CExchangeCardRet_ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GS2CExchangeCardRet_ErrorCode_value, data, "GS2CExchangeCardRet_ErrorCode")
	if err != nil {
		return err
	}
	*x = GS2CExchangeCardRet_ErrorCode(value)
	return nil
}

type GS2CDiscardRet_ErrorCode int32

const (
	GS2CDiscardRet_SUCCESS GS2CDiscardRet_ErrorCode = 1
	GS2CDiscardRet_FAIL    GS2CDiscardRet_ErrorCode = 2
)

var GS2CDiscardRet_ErrorCode_name = map[int32]string{
	1: "SUCCESS",
	2: "FAIL",
}
var GS2CDiscardRet_ErrorCode_value = map[string]int32{
	"SUCCESS": 1,
	"FAIL":    2,
}

func (x GS2CDiscardRet_ErrorCode) Enum() *GS2CDiscardRet_ErrorCode {
	p := new(GS2CDiscardRet_ErrorCode)
	*p = x
	return p
}
func (x GS2CDiscardRet_ErrorCode) String() string {
	return proto.EnumName(GS2CDiscardRet_ErrorCode_name, int32(x))
}
func (x *GS2CDiscardRet_ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GS2CDiscardRet_ErrorCode_value, data, "GS2CDiscardRet_ErrorCode")
	if err != nil {
		return err
	}
	*x = GS2CDiscardRet_ErrorCode(value)
	return nil
}

type LackCard struct {
	PlayerId         *int32    `protobuf:"varint,1,req,name=playerId" json:"playerId,omitempty"`
	Type             *CardType `protobuf:"varint,2,req,name=type,enum=pb.CardType" json:"type,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *LackCard) Reset()         { *m = LackCard{} }
func (m *LackCard) String() string { return proto.CompactTextString(m) }
func (*LackCard) ProtoMessage()    {}

func (m *LackCard) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *LackCard) GetType() CardType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return CardType_Wan
}

type CardInfo struct {
	PlayerId         *int32      `protobuf:"varint,1,req,name=playerId" json:"playerId,omitempty"`
	CardOid          *int32      `protobuf:"varint,2,req" json:"CardOid,omitempty"`
	CardId           *int32      `protobuf:"varint,3,req" json:"CardId,omitempty"`
	Status           *CardStatus `protobuf:"varint,4,req,enum=pb.CardStatus" json:"Status,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *CardInfo) Reset()         { *m = CardInfo{} }
func (m *CardInfo) String() string { return proto.CompactTextString(m) }
func (*CardInfo) ProtoMessage()    {}

func (m *CardInfo) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *CardInfo) GetCardOid() int32 {
	if m != nil && m.CardOid != nil {
		return *m.CardOid
	}
	return 0
}

func (m *CardInfo) GetCardId() int32 {
	if m != nil && m.CardId != nil {
		return *m.CardId
	}
	return 0
}

func (m *CardInfo) GetStatus() CardStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return CardStatus_noDeal
}

type BattlePlayerInfo struct {
	Side             *BattleSide `protobuf:"varint,1,req,name=side,enum=pb.BattleSide" json:"side,omitempty"`
	IsOwner          *bool       `protobuf:"varint,2,req,name=isOwner" json:"isOwner,omitempty"`
	Player           *PlayerInfo `protobuf:"bytes,3,req,name=player" json:"player,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *BattlePlayerInfo) Reset()         { *m = BattlePlayerInfo{} }
func (m *BattlePlayerInfo) String() string { return proto.CompactTextString(m) }
func (*BattlePlayerInfo) ProtoMessage()    {}

func (m *BattlePlayerInfo) GetSide() BattleSide {
	if m != nil && m.Side != nil {
		return *m.Side
	}
	return BattleSide_east
}

func (m *BattlePlayerInfo) GetIsOwner() bool {
	if m != nil && m.IsOwner != nil {
		return *m.IsOwner
	}
	return false
}

func (m *BattlePlayerInfo) GetPlayer() *PlayerInfo {
	if m != nil {
		return m.Player
	}
	return nil
}

type PlayerInfo struct {
	Oid              *int32  `protobuf:"varint,1,req,name=oid" json:"oid,omitempty"`
	NickName         *string `protobuf:"bytes,2,req,name=nickName" json:"nickName,omitempty"`
	HeadIcon         *string `protobuf:"bytes,3,req,name=headIcon" json:"headIcon,omitempty"`
	Gold             *int32  `protobuf:"varint,4,req,name=gold" json:"gold,omitempty"`
	Diamond          *int32  `protobuf:"varint,5,req,name=diamond" json:"diamond,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}

func (m *PlayerInfo) GetOid() int32 {
	if m != nil && m.Oid != nil {
		return *m.Oid
	}
	return 0
}

func (m *PlayerInfo) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *PlayerInfo) GetHeadIcon() string {
	if m != nil && m.HeadIcon != nil {
		return *m.HeadIcon
	}
	return ""
}

func (m *PlayerInfo) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *PlayerInfo) GetDiamond() int32 {
	if m != nil && m.Diamond != nil {
		return *m.Diamond
	}
	return 0
}

// ///////////////////////////////////////////////////////////////////
type C2GSLogin struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2GSLogin) Reset()         { *m = C2GSLogin{} }
func (m *C2GSLogin) String() string { return proto.CompactTextString(m) }
func (*C2GSLogin) ProtoMessage()    {}

func (m *C2GSLogin) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *C2GSLogin) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type GS2CLoginRet struct {
	ErrorCode        *GS2CLoginRet_ErrorCode `protobuf:"varint,1,req,name=errorCode,enum=pb.GS2CLoginRet_ErrorCode" json:"errorCode,omitempty"`
	PlayerInfo       *PlayerInfo             `protobuf:"bytes,2,opt,name=playerInfo" json:"playerInfo,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *GS2CLoginRet) Reset()         { *m = GS2CLoginRet{} }
func (m *GS2CLoginRet) String() string { return proto.CompactTextString(m) }
func (*GS2CLoginRet) ProtoMessage()    {}

func (m *GS2CLoginRet) GetErrorCode() GS2CLoginRet_ErrorCode {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return GS2CLoginRet_SUCCESS
}

func (m *GS2CLoginRet) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type C2GSEnterGame struct {
	Mode             *GameMode `protobuf:"varint,1,req,name=mode,enum=pb.GameMode" json:"mode,omitempty"`
	RoomId           *string   `protobuf:"bytes,2,opt,name=roomId" json:"roomId,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *C2GSEnterGame) Reset()         { *m = C2GSEnterGame{} }
func (m *C2GSEnterGame) String() string { return proto.CompactTextString(m) }
func (*C2GSEnterGame) ProtoMessage()    {}

func (m *C2GSEnterGame) GetMode() GameMode {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return GameMode_JoinRoom
}

func (m *C2GSEnterGame) GetRoomId() string {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return ""
}

type GS2CEnterGameRet struct {
	ErrorCode        *GS2CEnterGameRet_ErrorCode `protobuf:"varint,1,req,name=errorCode,enum=pb.GS2CEnterGameRet_ErrorCode" json:"errorCode,omitempty"`
	Mode             *GameMode                   `protobuf:"varint,2,req,name=mode,enum=pb.GameMode" json:"mode,omitempty"`
	RoomId           *string                     `protobuf:"bytes,3,req,name=roomId" json:"roomId,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *GS2CEnterGameRet) Reset()         { *m = GS2CEnterGameRet{} }
func (m *GS2CEnterGameRet) String() string { return proto.CompactTextString(m) }
func (*GS2CEnterGameRet) ProtoMessage()    {}

func (m *GS2CEnterGameRet) GetErrorCode() GS2CEnterGameRet_ErrorCode {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return GS2CEnterGameRet_SUCCESS
}

func (m *GS2CEnterGameRet) GetMode() GameMode {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return GameMode_JoinRoom
}

func (m *GS2CEnterGameRet) GetRoomId() string {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return ""
}

type GS2CUpdateRoomInfo struct {
	Player           []*BattlePlayerInfo        `protobuf:"bytes,1,rep,name=player" json:"player,omitempty"`
	Status           *GS2CUpdateRoomInfo_Status `protobuf:"varint,2,req,name=status,enum=pb.GS2CUpdateRoomInfo_Status" json:"status,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *GS2CUpdateRoomInfo) Reset()         { *m = GS2CUpdateRoomInfo{} }
func (m *GS2CUpdateRoomInfo) String() string { return proto.CompactTextString(m) }
func (*GS2CUpdateRoomInfo) ProtoMessage()    {}

func (m *GS2CUpdateRoomInfo) GetPlayer() []*BattlePlayerInfo {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *GS2CUpdateRoomInfo) GetStatus() GS2CUpdateRoomInfo_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return GS2CUpdateRoomInfo_ADD
}

type GS2CBattleStart struct {
	DealerId         *int32      `protobuf:"varint,1,req,name=dealerId" json:"dealerId,omitempty"`
	CardList         []*CardInfo `protobuf:"bytes,2,rep,name=cardList" json:"cardList,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GS2CBattleStart) Reset()         { *m = GS2CBattleStart{} }
func (m *GS2CBattleStart) String() string { return proto.CompactTextString(m) }
func (*GS2CBattleStart) ProtoMessage()    {}

func (m *GS2CBattleStart) GetDealerId() int32 {
	if m != nil && m.DealerId != nil {
		return *m.DealerId
	}
	return 0
}

func (m *GS2CBattleStart) GetCardList() []*CardInfo {
	if m != nil {
		return m.CardList
	}
	return nil
}

type C2GSExchangeCard struct {
	CardOid          []int32 `protobuf:"varint,1,rep,name=cardOid" json:"cardOid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2GSExchangeCard) Reset()         { *m = C2GSExchangeCard{} }
func (m *C2GSExchangeCard) String() string { return proto.CompactTextString(m) }
func (*C2GSExchangeCard) ProtoMessage()    {}

func (m *C2GSExchangeCard) GetCardOid() []int32 {
	if m != nil {
		return m.CardOid
	}
	return nil
}

type GS2CExchangeCardRet struct {
	ErrorCode        *GS2CExchangeCardRet_ErrorCode `protobuf:"varint,1,req,name=errorCode,enum=pb.GS2CExchangeCardRet_ErrorCode" json:"errorCode,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *GS2CExchangeCardRet) Reset()         { *m = GS2CExchangeCardRet{} }
func (m *GS2CExchangeCardRet) String() string { return proto.CompactTextString(m) }
func (*GS2CExchangeCardRet) ProtoMessage()    {}

func (m *GS2CExchangeCardRet) GetErrorCode() GS2CExchangeCardRet_ErrorCode {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return GS2CExchangeCardRet_SUCCESS
}

type GS2CUpdateExchangeOverPlayer struct {
	PlayerId         []int32 `protobuf:"varint,1,rep,name=playerId" json:"playerId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GS2CUpdateExchangeOverPlayer) Reset()         { *m = GS2CUpdateExchangeOverPlayer{} }
func (m *GS2CUpdateExchangeOverPlayer) String() string { return proto.CompactTextString(m) }
func (*GS2CUpdateExchangeOverPlayer) ProtoMessage()    {}

func (m *GS2CUpdateExchangeOverPlayer) GetPlayerId() []int32 {
	if m != nil {
		return m.PlayerId
	}
	return nil
}

type GS2CUpdateCardInfoAfterExchange struct {
	CardList         []*CardInfo `protobuf:"bytes,1,rep,name=cardList" json:"cardList,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GS2CUpdateCardInfoAfterExchange) Reset()         { *m = GS2CUpdateCardInfoAfterExchange{} }
func (m *GS2CUpdateCardInfoAfterExchange) String() string { return proto.CompactTextString(m) }
func (*GS2CUpdateCardInfoAfterExchange) ProtoMessage()    {}

func (m *GS2CUpdateCardInfoAfterExchange) GetCardList() []*CardInfo {
	if m != nil {
		return m.CardList
	}
	return nil
}

type C2GSSelectLack struct {
	Type             *CardType `protobuf:"varint,1,req,name=type,enum=pb.CardType" json:"type,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *C2GSSelectLack) Reset()         { *m = C2GSSelectLack{} }
func (m *C2GSSelectLack) String() string { return proto.CompactTextString(m) }
func (*C2GSSelectLack) ProtoMessage()    {}

func (m *C2GSSelectLack) GetType() CardType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return CardType_Wan
}

type GS2CSelectLackRet struct {
	LackCard         []*LackCard `protobuf:"bytes,1,rep,name=lackCard" json:"lackCard,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GS2CSelectLackRet) Reset()         { *m = GS2CSelectLackRet{} }
func (m *GS2CSelectLackRet) String() string { return proto.CompactTextString(m) }
func (*GS2CSelectLackRet) ProtoMessage()    {}

func (m *GS2CSelectLackRet) GetLackCard() []*LackCard {
	if m != nil {
		return m.LackCard
	}
	return nil
}

type GS2CDiscardTimeOut struct {
	PlayerId         *int32 `protobuf:"varint,1,req,name=playerId" json:"playerId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GS2CDiscardTimeOut) Reset()         { *m = GS2CDiscardTimeOut{} }
func (m *GS2CDiscardTimeOut) String() string { return proto.CompactTextString(m) }
func (*GS2CDiscardTimeOut) ProtoMessage()    {}

func (m *GS2CDiscardTimeOut) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

type C2GSDiscard struct {
	CardId           *int32          `protobuf:"varint,1,req,name=cardId" json:"cardId,omitempty"`
	Status           *DisacardStatus `protobuf:"varint,2,req,name=status,enum=pb.DisacardStatus" json:"status,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *C2GSDiscard) Reset()         { *m = C2GSDiscard{} }
func (m *C2GSDiscard) String() string { return proto.CompactTextString(m) }
func (*C2GSDiscard) ProtoMessage()    {}

func (m *C2GSDiscard) GetCardId() int32 {
	if m != nil && m.CardId != nil {
		return *m.CardId
	}
	return 0
}

func (m *C2GSDiscard) GetStatus() DisacardStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return DisacardStatus_default
}

type GS2CDiscardRet struct {
	ErrorCode        *GS2CDiscardRet_ErrorCode `protobuf:"varint,1,req,name=errorCode,enum=pb.GS2CDiscardRet_ErrorCode" json:"errorCode,omitempty"`
	Card             []*CardInfo               `protobuf:"bytes,2,rep,name=card" json:"card,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *GS2CDiscardRet) Reset()         { *m = GS2CDiscardRet{} }
func (m *GS2CDiscardRet) String() string { return proto.CompactTextString(m) }
func (*GS2CDiscardRet) ProtoMessage()    {}

func (m *GS2CDiscardRet) GetErrorCode() GS2CDiscardRet_ErrorCode {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return GS2CDiscardRet_SUCCESS
}

func (m *GS2CDiscardRet) GetCard() []*CardInfo {
	if m != nil {
		return m.Card
	}
	return nil
}

type GS2CDealCard struct {
	PlayerId         *int32    `protobuf:"varint,1,req,name=playerId" json:"playerId,omitempty"`
	Card             *CardInfo `protobuf:"bytes,2,req,name=card" json:"card,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *GS2CDealCard) Reset()         { *m = GS2CDealCard{} }
func (m *GS2CDealCard) String() string { return proto.CompactTextString(m) }
func (*GS2CDealCard) ProtoMessage()    {}

func (m *GS2CDealCard) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *GS2CDealCard) GetCard() *CardInfo {
	if m != nil {
		return m.Card
	}
	return nil
}

type C2GSWin struct {
	PlayerId         *int32 `protobuf:"varint,1,req,name=playerId" json:"playerId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2GSWin) Reset()         { *m = C2GSWin{} }
func (m *C2GSWin) String() string { return proto.CompactTextString(m) }
func (*C2GSWin) ProtoMessage()    {}

func (m *C2GSWin) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

type GS2CWinRet struct {
	PlayerId         *int32 `protobuf:"varint,2,req,name=playerId" json:"playerId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GS2CWinRet) Reset()         { *m = GS2CWinRet{} }
func (m *GS2CWinRet) String() string { return proto.CompactTextString(m) }
func (*GS2CWinRet) ProtoMessage()    {}

func (m *GS2CWinRet) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.GameMode", GameMode_name, GameMode_value)
	proto.RegisterEnum("pb.BattleSide", BattleSide_name, BattleSide_value)
	proto.RegisterEnum("pb.CardStatus", CardStatus_name, CardStatus_value)
	proto.RegisterEnum("pb.CardType", CardType_name, CardType_value)
	proto.RegisterEnum("pb.DisacardStatus", DisacardStatus_name, DisacardStatus_value)
	proto.RegisterEnum("pb.GS2CLoginRet_ErrorCode", GS2CLoginRet_ErrorCode_name, GS2CLoginRet_ErrorCode_value)
	proto.RegisterEnum("pb.GS2CEnterGameRet_ErrorCode", GS2CEnterGameRet_ErrorCode_name, GS2CEnterGameRet_ErrorCode_value)
	proto.RegisterEnum("pb.GS2CUpdateRoomInfo_Status", GS2CUpdateRoomInfo_Status_name, GS2CUpdateRoomInfo_Status_value)
	proto.RegisterEnum("pb.GS2CExchangeCardRet_ErrorCode", GS2CExchangeCardRet_ErrorCode_name, GS2CExchangeCardRet_ErrorCode_value)
	proto.RegisterEnum("pb.GS2CDiscardRet_ErrorCode", GS2CDiscardRet_ErrorCode_name, GS2CDiscardRet_ErrorCode_value)
}
