//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: mahjon.proto
namespace pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LackCard")]
  public partial class LackCard : global::ProtoBuf.IExtensible
  {
    public LackCard() {}
    
    private int _playerOID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerOID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerOID
    {
      get { return _playerOID; }
      set { _playerOID = value; }
    }
    private pb.CardType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.CardType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardInfo")]
  public partial class CardInfo : global::ProtoBuf.IExtensible
  {
    public CardInfo() {}
    
    private int _playerOID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerOID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerOID
    {
      get { return _playerOID; }
      set { _playerOID = value; }
    }
    private int _OID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"OID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OID
    {
      get { return _OID; }
      set { _OID = value; }
    }
    private int _ID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private pb.CardStatus _Status;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.CardStatus Status
    {
      get { return _Status; }
      set { _Status = value; }
    }
    private bool _fromOther = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fromOther", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool fromOther
    {
      get { return _fromOther; }
      set { _fromOther = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private int _OID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"OID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OID
    {
      get { return _OID; }
      set { _OID = value; }
    }
    private string _NickName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"NickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string NickName
    {
      get { return _NickName; }
      set { _NickName = value; }
    }
    private string _HeadIcon;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"HeadIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string HeadIcon
    {
      get { return _HeadIcon; }
      set { _HeadIcon = value; }
    }
    private int _Gold;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Gold
    {
      get { return _Gold; }
      set { _Gold = value; }
    }
    private int _Fangka;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Fangka", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Fangka
    {
      get { return _Fangka; }
      set { _Fangka = value; }
    }
    private pb.MahjonSide _Side = pb.MahjonSide.DEFAULT;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Side", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(pb.MahjonSide.DEFAULT)]
    public pb.MahjonSide Side
    {
      get { return _Side; }
      set { _Side = value; }
    }
    private bool _IsOwner = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"IsOwner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsOwner
    {
      get { return _IsOwner; }
      set { _IsOwner = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameOverInfo")]
  public partial class GameOverInfo : global::ProtoBuf.IExtensible
  {
    public GameOverInfo() {}
    
    private pb.PlayerInfo _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public pb.PlayerInfo player
    {
      get { return _player; }
      set { _player = value; }
    }
    private int _fan;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fan
    {
      get { return _fan; }
      set { _fan = value; }
    }
    private readonly global::System.Collections.Generic.List<pb.CardInfo> _cardList = new global::System.Collections.Generic.List<pb.CardInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.CardInfo> cardList
    {
      get { return _cardList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSLogin")]
  public partial class C2GSLogin : global::ProtoBuf.IExtensible
  {
    public C2GSLogin() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CLoginRet")]
  public partial class GS2CLoginRet : global::ProtoBuf.IExtensible
  {
    public GS2CLoginRet() {}
    
    private pb.GS2CLoginRet.ErrorCode _errorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.GS2CLoginRet.ErrorCode errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private pb.PlayerInfo _playerInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb.PlayerInfo playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACCOUNT_ERROR", Value=2)]
      ACCOUNT_ERROR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PASSWORD_ERROR", Value=3)]
      PASSWORD_ERROR = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=4)]
      FAIL = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSEnterGame")]
  public partial class C2GSEnterGame : global::ProtoBuf.IExtensible
  {
    public C2GSEnterGame() {}
    
    private pb.GameType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.GameType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private pb.EnterMode _mode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.EnterMode mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private string _roomId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CEnterGameRet")]
  public partial class GS2CEnterGameRet : global::ProtoBuf.IExtensible
  {
    public GS2CEnterGameRet() {}
    
    private pb.GS2CEnterGameRet.ErrorCode _errorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.GS2CEnterGameRet.ErrorCode errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private pb.GameType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.GameType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _roomId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=2)]
      FAIL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_COUNT_LIMITE", Value=3)]
      PLAYER_COUNT_LIMITE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROOM_NOT_EXIST", Value=4)]
      ROOM_NOT_EXIST = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_EMPTY_ROOM", Value=5)]
      NO_EMPTY_ROOM = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CUpdateRoomMember")]
  public partial class GS2CUpdateRoomMember : global::ProtoBuf.IExtensible
  {
    public GS2CUpdateRoomMember() {}
    
    private readonly global::System.Collections.Generic.List<pb.PlayerInfo> _player = new global::System.Collections.Generic.List<pb.PlayerInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.PlayerInfo> player
    {
      get { return _player; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CBattleStart")]
  public partial class GS2CBattleStart : global::ProtoBuf.IExtensible
  {
    public GS2CBattleStart() {}
    
    private int _dealerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dealerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dealerId
    {
      get { return _dealerId; }
      set { _dealerId = value; }
    }
    private readonly global::System.Collections.Generic.List<pb.CardInfo> _cardList = new global::System.Collections.Generic.List<pb.CardInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.CardInfo> cardList
    {
      get { return _cardList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSExchangeCard")]
  public partial class C2GSExchangeCard : global::ProtoBuf.IExtensible
  {
    public C2GSExchangeCard() {}
    
    private readonly global::System.Collections.Generic.List<int> _cardOIDList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cardOIDList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cardOIDList
    {
      get { return _cardOIDList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CExchangeCardRet")]
  public partial class GS2CExchangeCardRet : global::ProtoBuf.IExtensible
  {
    public GS2CExchangeCardRet() {}
    
    private pb.ExchangeType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.ExchangeType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<pb.CardInfo> _cardList = new global::System.Collections.Generic.List<pb.CardInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.CardInfo> cardList
    {
      get { return _cardList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSSelectLack")]
  public partial class C2GSSelectLack : global::ProtoBuf.IExtensible
  {
    public C2GSSelectLack() {}
    
    private pb.CardType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.CardType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CSelectLackRet")]
  public partial class GS2CSelectLackRet : global::ProtoBuf.IExtensible
  {
    public GS2CSelectLackRet() {}
    
    private readonly global::System.Collections.Generic.List<pb.LackCard> _lackCard = new global::System.Collections.Generic.List<pb.LackCard>();
    [global::ProtoBuf.ProtoMember(1, Name=@"lackCard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.LackCard> lackCard
    {
      get { return _lackCard; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CTurnToNext")]
  public partial class GS2CTurnToNext : global::ProtoBuf.IExtensible
  {
    public GS2CTurnToNext() {}
    
    private int _playerOID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerOID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerOID
    {
      get { return _playerOID; }
      set { _playerOID = value; }
    }
    private pb.CardInfo _drawCard = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"drawCard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb.CardInfo drawCard
    {
      get { return _drawCard; }
      set { _drawCard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CInterruptAction")]
  public partial class GS2CInterruptAction : global::ProtoBuf.IExtensible
  {
    public GS2CInterruptAction() {}
    
    private readonly global::System.Collections.Generic.List<pb.ProcType> _procList = new global::System.Collections.Generic.List<pb.ProcType>();
    [global::ProtoBuf.ProtoMember(1, Name=@"procList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<pb.ProcType> procList
    {
      get { return _procList; }
    }
  
    private pb.CardInfo _drawCard = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"drawCard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb.CardInfo drawCard
    {
      get { return _drawCard; }
      set { _drawCard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSInterruptActionRet")]
  public partial class C2GSInterruptActionRet : global::ProtoBuf.IExtensible
  {
    public C2GSInterruptActionRet() {}
    
    private pb.ProcType _procType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"procType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.ProcType procType
    {
      get { return _procType; }
      set { _procType = value; }
    }
    private pb.CardInfo _drawCard = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"drawCard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb.CardInfo drawCard
    {
      get { return _drawCard; }
      set { _drawCard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CBroadcastProc")]
  public partial class GS2CBroadcastProc : global::ProtoBuf.IExtensible
  {
    public GS2CBroadcastProc() {}
    
    private int _procPlayer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"procPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int procPlayer
    {
      get { return _procPlayer; }
      set { _procPlayer = value; }
    }
    private pb.ProcType _procType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"procType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.ProcType procType
    {
      get { return _procType; }
      set { _procType = value; }
    }
    private readonly global::System.Collections.Generic.List<pb.CardInfo> _cardList = new global::System.Collections.Generic.List<pb.CardInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.CardInfo> cardList
    {
      get { return _cardList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CGameOver")]
  public partial class GS2CGameOver : global::ProtoBuf.IExtensible
  {
    public GS2CGameOver() {}
    
    private readonly global::System.Collections.Generic.List<pb.GameOverInfo> _list = new global::System.Collections.Generic.List<pb.GameOverInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.GameOverInfo> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameType")]
    public enum GameType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"XueZhan", Value=1)]
      XueZhan = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"XueLiu", Value=2)]
      XueLiu = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DouDiZhu", Value=3)]
      DouDiZhu = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EnterMode")]
    public enum EnterMode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateRoom", Value=1)]
      CreateRoom = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JoinRoom", Value=2)]
      JoinRoom = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QuickEnter", Value=3)]
      QuickEnter = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MahjonSide")]
    public enum MahjonSide
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEFAULT", Value=1)]
      DEFAULT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EAST", Value=2)]
      EAST = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUTH", Value=3)]
      SOUTH = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WEST", Value=4)]
      WEST = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NORTH", Value=5)]
      NORTH = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CardStatus")]
    public enum CardStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Wall", Value=1)]
      Wall = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InHand", Value=2)]
      InHand = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"P", Value=3)]
      P = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"G", Value=4)]
      G = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Dis", Value=5)]
      Dis = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Deal", Value=6)]
      Deal = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Hu", Value=7)]
      Hu = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ExchangeType")]
    public enum ExchangeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClockWise", Value=1)]
      ClockWise = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AntiClock", Value=2)]
      AntiClock = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Opposite", Value=3)]
      Opposite = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CardType")]
    public enum CardType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Default", Value=1)]
      Default = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Wan", Value=2)]
      Wan = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Tiao", Value=3)]
      Tiao = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Tong", Value=4)]
      Tong = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProcType")]
    public enum ProcType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Proc_Hu", Value=1)]
      Proc_Hu = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Proc_Gang", Value=2)]
      Proc_Gang = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Proc_Peng", Value=3)]
      Proc_Peng = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Proc_Discard", Value=4)]
      Proc_Discard = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Proc_Pass", Value=5)]
      Proc_Pass = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TurnSwitchType")]
    public enum TurnSwitchType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Normal", Value=1)]
      Normal = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JustCanDiscard", Value=2)]
      JustCanDiscard = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotDrawCard", Value=3)]
      NotDrawCard = 3
    }
  
}